//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCH.CloudDrive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDCH.CloudDrive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Logging&quot;: {
        ///    &quot;LogLevel&quot;: {
        ///      &quot;Default&quot;: &quot;Information&quot;,
        ///      &quot;Microsoft&quot;: &quot;Warning&quot;,
        ///      &quot;Microsoft.Hosting.Lifetime&quot;: &quot;Information&quot;
        ///    }
        ///  },
        ///  &quot;AllowedHosts&quot;: &quot;*&quot;,
        ///  &quot;MailSettings&quot;: {
        ///    &quot;MailUser&quot;: &quot;mifmasterz@outlook.com&quot;,
        ///    &quot;MailPassword&quot;: &quot;123qweasd&quot;,
        ///    &quot;MailServer&quot;: &quot;smtp.outlook.com&quot;,
        ///
        ///    //&quot;MailUser&quot;: &quot;apbn.bogor@gmail.com&quot;,
        ///    //&quot;MailPassword&quot;: &quot;apbn123qweasd&quot;,
        ///    //&quot;MailServer&quot;: &quot;smtp.gmail.com&quot;,
        ///    &quot;SendGridKey&quot;: &quot;SG.2x5VfPP8Ta-M_qpzpTpoCA.tJCVrWGdFqPS0ej [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appsettings_json {
            get {
                return ResourceManager.GetString("appsettings.json", resourceCulture);
            }
        }
    }
}
